### PR TITLE
hotfix/1.47.13

### LINKED ISSUE #1653: Misplaced 'Recent Activity' popover
**Describe the bug**
The 'Recent Activity' popover is incorrectly placed on mobile, which makes it impossible to read.

**To Reproduce**
1. On mobile, connect wallet
2. Tap on the 'activity' icon in the top nav. 
3. View the popover.

**Expected behavior**
The popover should be positioned within the viewport.

**Screenshots**

Screen Shot 2022-04-06 at 3 16 37 PM

### PR DESCRIPTION
**Pull request by evgenyboxer**
# Description

This PR fixes the issue described in #1653 where the popover is basically unreachable on mobile for the account/recent activity.

Fixes #1653 

Here's how it looks now:
Screen Shot 2022-04-08 at 1 13 11 pm

Screen Shot 2022-04-08 at 1 15 15 pm

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Try to open the recent activity / account on mobile.

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

File: src/components/_global/BalPopover/BalPopover.vue [hunk 1]
```diff
@@ -114,8 +116,10 @@ watch(popoverOpened, () => {
 }
 
 .align-center-transform {
-  -webkit-transform: translateX(-50%);
-  transform: translateX(-50%);
+  -webkit-transform: translateX(
+    -webkit-calc(-50% + v-bind(activatorHalfWidthPx))
+  );
+  transform: translateX(calc(-50% + v-bind(activatorHalfWidthPx)));
```
Comment (evgenyboxer) [inline src/components/_global/BalPopover/BalPopover.vue:122]: The centered position looks better when its shifted by half of the width of the activator.

File: src/components/navs/AppNav/AppNavAccountBtn.vue [hunk 2]
```diff
@@ -1,5 +1,9 @@
 <template>
-  <BalPopover no-pad>
+  <BalPopover
+    no-pad
+    :align="isMobile ? 'right' : undefined"
+    :detached="isMobile ? true : undefined"
```
Comment (evgenyboxer) [inline src/components/navs/AppNav/AppNavAccountBtn.vue:5]: Since I only need these on mobile - passing `undefined` would basically mean these props won't be passed down.

**Review by timjrobinson — APPROVED** [review]
LGTM. We could have undone the earlier changes to PopOver as they were for the vebal table but we ended up going with a modal anyway, but if this is better than that works.
