### PR TITLE
Fix return route for veBAL investment

### LINKED ISSUE #1569: When closing the 'Invest' flow, the user should be taken back to where they came from
**Describe the bug**
Right now, if a user goes from the veBAL page and hits the plus button to add liquidity to 80BAL/20WETH, and then close using the 'x' button, they are taken to the pool page. When closing the 'Invest' flow, the user should be taken back to where they came from. In this case, they should be returned back to the veBAL page. 

See screen recording.

https://www.loom.com/share/a13ebc8b39f8430397112bf2108773f0

**To Reproduce**
1. Go to veBAL
2. Click on plus button to add liquidity. 
3. Hit the 'x' button

**Expected behavior**
User should be returned to where they came from.

### PR DESCRIPTION
**Pull request by garethfuller**
# Description

Fixes #1569 
- When navigating to the invest flow from the veBAL page, should redirect back to veBAL page on clicking to close
- Refactors handling of return route into it's own composable

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test that you are returned to the veBAL page if you try to invest in BAL/WETH from there
- [ ] Test that you are returned to the pool page if you click invest from there

## Visual context

n/a

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

File: src/composables/useReturnRoute.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+      if (queryReturnParams) {
+        return {
+          name: queryReturnRoute,
+          params: JSON.parse(queryReturnParams)
+        };
+      }
+
+      return { name: queryReturnRoute };
+    } else if (to) return to;
```
Comment (timjrobinson) [inline src/composables/useReturnRoute.ts:20]:
```suggestion
    } 
    
    if (to) {
        return to;
    }
```

**Review by timjrobinson — APPROVED** [review]
LGTM, only one minor change.

File: src/composables/useReturnRoute.ts (hunk 1 above)
Comment (garethfuller) [reply src/composables/useReturnRoute.ts:20]: Why break this into it's own if?

**Review by evgenyboxer — APPROVED** [review]
