### PR TITLE
Bugfix: Reload page on dynamic module load error

### LINKED ISSUE #2778: Failed to fetch dynamically imported module
**Describe the bug**

Dynamic modules cannot be loaded after a deployment. 

**To Reproduce**

1. Keep an opened tab with balancer.fi
2. Wait for a new deployment
3. Try to navigate to another route with header links

**Expected behavior**

Automatic reload or reload + user notification.

### PR DESCRIPTION
**Pull request by agualis**
# Description

Workaround for [Failed to fetch dynamically imported module error.](https://github.com/vitejs/vite/issues/11804).

Closes #2778

Sentry link: https://balancer-labs.sentry.io/issues/3922269920/?project=5725878

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

1. Open https://beta.balancer.fi/#/
2. Wait for merge and deploy and check if the error is gone. 

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

File: src/plugins/router/index.ts [hunk 1]
```diff
@@ -204,4 +204,13 @@ const router = createRouter({
   },
 });
 
+router.onError((error, to) => {
+  if (error.message.includes('Failed to fetch dynamically imported module')) {
+    console.log('ERROR IN ROUTE; ', error.message);
```
Comment (garethfuller) [inline src/plugins/router/index.ts:209]: Maybe we should capture this in Sentry so we know when it's happening?

Comment (agualis) [reply src/plugins/router/index.ts]: Good idea. Done.

**Review by garethfuller — APPROVED** [review]

**Review by alter-eggo — APPROVED** [review]
